camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  filter:
    create: All Tasks

server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:./camunda-demo
    driverClassName: org.h2.Driver
    username: sa
    password: sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database-platform: org.hibernate.dialect.H2Dialect